name: Unit Testing

on:
  workflow_run:
    workflows: ["codeQuality"]
    types:
      - completed

jobs:
  unittest:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run Tests with Pytest
        run: pytest
